run_params:
  class_name: delightPZ
  run_name: test_delightPZ
  rand_width: 0.025
  rand_zmin: 0.0
  rand_zmax: 3.0
  nzbins: 301
  dlght_redshiftMin: 0.1
  dlght_redshiftMax: 3.101
  dlght_redshiftNumBinsGPpred: 300
  dlght_redshiftBinSize: 0.001
  dlght_redshiftDisBinSize: 0.2
  tempdir: "./tmp"
  tempdatadir: "./tmp/delight_data"
  delightparamfile: "parametersTest.cfg"
  dlght_tutorialmode: False


